approvals:
  # check will fail if there is no approval
  minimum: 1
  groups:
    - name: 'PyTorch Lightning'
      from:
        - awaelchli
        - Borda
        - carmocca
        - ethanwharris
        - kaushikb11
        - krshrimali
        - otaj
        - rohitgr7
        - tchaton
        - williamFalcon
