approvals:
  # check will fail if there is no approval
  minimum: 1
  groups:
    - name: 'Lightning Apps'
      from:
        - alecmerdler
        - awaelchli
        - hhsecond
        - lantiga
        - manskx
        - nohalon
        - tchaton
