# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - "master"
      - "release/*"
      - "refs/tags/*"

pr: none

schedules:
  - cron: "0 0 * * *" # At the end of every day
    displayName: Daily midnight benchmark
    branches:
      include:
        - "master"

jobs:
  - job: benchmarks
    timeoutInMinutes: "90"
    cancelTimeoutInMinutes: "2"
    pool: azure-jirka-spot
    container:
      image: "pytorchlightning/pytorch_lightning:base-cuda-py3.9-torch1.11"
      options: "--runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all --shm-size=32g"
    workspace:
      clean: all

    steps:

    - bash: |
        pip install -e . -r requirements/pytorch/strategies.txt
        pip list
      env:
        PACKAGE_NAME: pytorch
        FREEZE_REQUIREMENTS: 1
      displayName: 'Install package'

    - bash: python -m pytest benchmarks -v --durations=0
      env:
        PL_RUNNING_BENCHMARKS: 1
        PL_RUN_CUDA_TESTS: "1"
      workingDirectory: tests/tests_pytorch
      displayName: 'Testing: PyTorch benchmarks'
